SELECT * FROM FoodTruck
SELECT * FROM Menu
SELECT * FROM Hours
SELECT * FROM Rating
SELECT * FROM Location
SELECT * FROM Customer
SELECT * FROM Employee
SELECT * FROM FoodTruckCustomer
SELECT * FROM FoodTruckLocation
SELECT * FROM CustomerRating
